### ISSUE TITLE
LAMMPS fail with the potential from PROPhet

### ISSUE THREAD

**Issue by Nanco-L** [biklooost/PROPhet#1]
Hi, I want to run MD simulation with PROPhet potential.
And I generated the potential_C file using tutorial dataset.
But LAMMPS MD failed with the segmentation fault error in the atom initializing process.
I don't know what is the reason.

I attach the lammps log file and generated potential file.

[lammps_PROPhet_Test.zip](https://github.com/biklooost/PROPhet/files/1073652/lammps_PROPhet_Test.zip)

**Comment by Nanco-L** [comment]
More info.
segfault is occur at /src/pair_nn.cpp, Line 238.

the size of setflag is 1 but for loop starts i=1 and call setflag[i] which means setflag[1]

**Comment by Nanco-L** [comment]
Problem solved. Sorry for inconvenience.
Its just lammps input file mistake

**Comment by ipudu** [comment]
Hi, can you please share the detail how did you solve this problem? thanks! @Nanco-L

**Comment by ipudu** [comment]
Hi, I got the same error from lammps. Can you please share the details that how did you solve this problem? thanks!

**Comment by ipudu** [comment]
Hi, I got the same error from lammps. Can you please share the details that how did you solve this problem? thanks! @Nanco-L

**Comment by Nanco-L** [comment]
Which error occurs in your case? I cannot help you without this information. Plus, I do not use PROPhet for my research. We have our own code for NN training/MD simulation. So, for better response, you need to ask this question to the developer of PROPhet code. @ipudu

**Comment by ipudu** [comment]
I got the similar segmentation fault like your case:

Initializing atom type 1 with file potential_C
Caught error: Segmentation fault (signal 11)
Segmentation fault

Do you have any ideas? I am just wondering how did you solve the problem for your case. If you don't mind, can you send me the lammps input for your case after correction? I used the example data to get nn potential and then I builded the lammps data file for this system. If you got time, please check attachment for details. I really appreciate it. 
[nn.zip](https://github.com/biklooost/PROPhet/files/1283207/nn.zip)

Thank you for your suggestion.  Is your code publicly available? would you mind drop a link of the code repo or the article? Thank you! @Nanco-L
