### ISSUE TITLE
link with lammps

### ISSUE THREAD

**Issue by comet-group** [biklooost/PROPhet#2]
Hope someone can help me with Floating point exception (8). PROPhet and Lammps run fine. The problem appears only when the nn potentials are called.

I tried with various version of lammps but no difference.

Thanks.

[node004:23970] *** Process received signal ***
[node004:23970] Signal: Floating point exception (8)
[node004:23970] Signal code:  (7)
[node004:23970] Failing at address: 0xa82b65
[node004:23970] [ 0] /lib64/libpthread.so.0() [0x31fea0f4a0]
[node004:23970] [ 1] /shared/lammps/021015/bin/lmp_mpi(_ZN14Neural_network11evaluate_MDERSt6vectorIdSaIdEE+0x315) [0xa82b65]
[node004:23970] [ 2] /shared/lammps/021015/bin/lmp_mpi(_ZN9Potential11evaluate_MDEiiRSt6vectorIdSaIdEE+0x9b) [0x9f428b]
[node004:23970] [ 3] /shared/lammps/021015/bin/lmp_mpi(_ZN9LAMMPS_NS6PairNN7computeEii+0x46b) [0x9d370b]
[node004:23970] [ 4] /shared/lammps/021015/bin/lmp_mpi(_ZN9LAMMPS_NS3Min5setupEv+0x5de) [0x6e810e]
[node004:23970] [ 5] /shared/lammps/021015/bin/lmp_mpi(_ZN9LAMMPS_NS8Minimize7commandEiPPc+0x199) [0x6f6b29]
[node004:23970] [ 6] /shared/lammps/021015/bin/lmp_mpi(_ZN9LAMMPS_NS5Input15command_creatorINS_8MinimizeEEEvPNS_6LAMMPSEiPPc+0x29) [0x6d05a9]
[node004:23970] [ 7] /shared/lammps/021015/bin/lmp_mpi(_ZN9LAMMPS_NS5Input15execute_commandEv+0x22f7) [0x6cac57]
[node004:23970] [ 8] /shared/lammps/021015/bin/lmp_mpi(_ZN9LAMMPS_NS5Input4fileEv+0x1e0) [0x6c6fa0]
[node004:23970] [ 9] /shared/lammps/021015/bin/lmp_mpi(main+0x94) [0x6e3634]
[node004:23970] [10] /lib64/libc.so.6(__libc_start_main+0xfd) [0x31fe61ecdd]
[node004:23970] [11] /shared/lammps/021015/bin/lmp_mpi() [0x4b4e89]
[node004:23970] *** End of error message ***

**Comment by levilentz** [comment]
This was determined to be an error in the input data during training from user-generated VASP files. No issue with lammps linking.
