### ISSUE TITLE
documentation's tutorial results differ

### ISSUE THREAD

**Issue by EfremBraun** [biklooost/PROPhet#4]
The docs say that running the "input_train" example file with 300 iterations gives a network which gives an RMS error of 0.543206 when running "input_validate," but I'm needing around 12500 iterations to get to an RMS error that low. Unless I'm making an error (though I didn't touch the input files), this should probably be noted in the docs.

**Comment by levilentz** [comment]
Hi, 

I believe we had noted in the docs that as the weights are randomly generated, sometimes it will take longer to minimize. The data in the example files are very small, so achieving an exact result in two runs is very difficult. 

However, thank you for bringing this to my attention.  We are about to release a new version of the code, and will be sure to clarify this. 

Cheers,

Levi
