### ISSUE TITLE
docs feature request: sample input files for other codes

### ISSUE THREAD

**Issue by EfremBraun** [biklooost/PROPhet#5]
Would it be possible to get sample input files for Quantum Espresso and FHI-AIMS? The code's tutorial gives sample input files for VASP, but I'm planning on running it with a different code (CP2K, actually) and it'd be helpful to have other input files to help me understand how to write CP2K.cpp in the context of VASP.cpp, QE.cpp, and FHIAIMS.cpp. It'd probably also be helpful to people who want to use those other codes.

It might be helpful also to have a sample LAMMPS input file. I was able to get it working pretty fast, but it might help others.

**Comment by levilentz** [comment]
Hello Efrem,

We had emailed about this directly, but for other users: we will be releasing a new code that has a custom PROPhet XML file type. 

Cheers,

Levi
